spring :
  application:
    name: cloud-movie-ribbon

server:
  port: 8043
  #  servlet :

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

#配置负载均衡
#ribbon:
#  eureka:
#    enabled: false

