spring:
  application:
    name: cloud-movie
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
#      url: jdbc:mysql://123.207.228.185/dd?useUnicode=true&characterEncoding=utf-8
#      password: 123456
#      username: book
#      name: book
      url: jdbc:mysql://127.0.0.1:3306/dd?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT
      password: root
      username: root

server:
  port: 8045
  #  servlet :

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
